README.md, docs/src/components/HomepageFeatures/index.js, docs/src/components/HomepageFeatures/styles.module.css, docs/src/css/custom.css, docs/src/pages/index.js, packages/signalstory/README.md, sample/src/app/app.component.ts
Improve mobile view, fix error in Readme
=> Improve mobile view, fix error in Readme

docs/docs/immutable-store.md, docs/docs/plugins/_category_.json, docs/docs/plugins/custom-plugin.md, packages/signalstory/src/__tests__/helper.ts, packages/signalstory/src/__tests__/immutable-store.spec.ts, packages/signalstory/src/__tests__/store-mediator.spec.ts, packages/signalstory/src/__tests__/store-plugin-history.spec.ts, packages/signalstory/src/__tests__/store-plugin-persistence.spec.ts, packages/signalstory/src/__tests__/store.spec.ts, packages/signalstory/src/public-api.ts
Introducing deep freeze plugin
=> Introducing deep freeze plugin

packages/signalstory/src/lib/store-plugin-devtools/plugin-devtools.ts
Check browser support, Fix eslint issues
=> Check browser support, Fix eslint issues

packages/signalstory/src/__tests__/immutable-store.spec.ts, packages/signalstory/src/__tests__/store-mediator.spec.ts, packages/signalstory/src/lib/store-plugin-history/plugin-history.ts, packages/signalstory/src/lib/store-plugin-persistence/plugin-persistence.ts
swap any for unknown types for some internal functions to simplify type usage in tests
=> swap any for unknown types for some internal functions to simplify type usage in tests

package.json, packages/signalstory/package.json
=> Release 0.1.2

docs/docusaurus.config.js, docs/src/components/HomepageFeatures/index.js
- Add alt attribute to feature images
- Add missing meta attributes
=> docs: Improve SEO

docs/docusaurus.config.js, sample/src/app/app.component.ts, sample/src/app/state/books.effects.ts, sample/src/app/state/books.store.ts, sample/src/app/state/events.ts
- Improve Sample
- Set docusaurs trailing slashes configuration to false
=> docs: Improve sample and docs seo

packages/signalstory/package.json
=> Release 0.1.3

README.md, packages/signalstory/README.md
Include changelof notice in README
=> Include changelof notice in README

README.md, packages/signalstory/README.md, packages/signalstory/package.json
Bump angular peer dependency to 17 and typo fix in readme
=> Bump angular peer dependency to 17 and typo fix in readme

README.md
=> Improve sample

README.md, packages/signalstory/README.md, packages/signalstory/package.json
Last small fixes for Release 17.1.0 And Release
=> Last small fixes for Release 17.1.0

docs/docusaurus.config.js, docs/src/pages/index.js, packages/signalstory/package.json
=> Improve meta tags

packages/signalstory/src/lib/store.ts
Refactor pre and post processors to encapsulate successive processors. This adjustment aligns with standard middleware patterns, providing plugin creators with the flexibility to design order-sensitive plugins that may have dependencies on other plugins. Regular users should not notice any difference in the libraries's behavior.
=> Middleware Refactor: Successive Processors should be fully wraped by  Pre and Post Processors

package.json, packages/signalstory/README.md, packages/signalstory/package.json
Prepare package.json and README for Release 17.2.0
=> Release 17.2.0

README.md
Fix Readme linebreaks in featurelist
=> docs: fix readme linebreaks in featurelist

.commitlintrc.js, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .husky/commit-msg, .husky/pre-commit, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, package-lock.json, package.json
This PR introduces 
- `CONTRIBUTION` to guide futuure contribution efforts
- `CODE_OF_CONDUCT`
- Templates for issues and PRs
- `Commitlint` and `Husky` for convetions checks
- `Commitizen` for simplyfing commit messsages
=> chore: add ressources for contribution

.github/workflows/ci.yml
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
No workflows used
CI workflow for applyinng tests and checks to any PR
```
[ ] Yes
[x] No
```
=> ci: :ferris_wheel: add workflow for running tests and performing checks

.eslintignore
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
Linting fails for files in the `/dist` folder
Lint runs and files in `/dist` are ignored.
```
[ ] Yes
[x] No
```
=> chore: :hammer: add eslintignore

.github/workflows/ci.yml
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
CI Build fails because workspace project is not specified
CI build works
```
[ ] Yes
[x] No
```
=> ci: :ferris_wheel: specify project in build command

packages/signalstory/src/lib/store-snapshot.ts
```
[x] Bugfix
[ ] Feature
```
A snapshot stores the state of a store in a container. This works well for immutable stores, but could easily break, if the state is not deeply immutable.
If the store is not immutable, the state is deepcloned before taking the snapshot
```
[ ] Yes
[x] No
```
=> fix(core): :bug: clone store state prior to snapshot if the store is not immutable

docs/docs/Howto.md, docs/docs/building-blocks/event.md, docs/docs/configuration.md, docs/docs/immutable-store.md, docs/docs/plugins/history.md, docs/docs/plugins/logger.md, docs/docs/plugins/performance.md, docs/docs/state-snapshot.md
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
Enhance documentation: Add Howto.md for dynamically configuring store plugins based on the build
environment, update building-blocks/event.md for clarity, modify configuration.md and
immutable-store.md to reflect updated examples, and refine tips in plugins/history.md.
=> docs: :memo: add howtos and improve multiple doc pages

docs/docusaurus.config.js
```
[ ] Bugfix
[x] Feature
[x] Documentation content changes
```
No docsearch avalilable
You can now search the docs, Thanks algolia :D
=> docs: :memo: add algolia docsearch support

docs/src/css/custom.css, docs/src/pages/index.js, docs/src/pages/index.module.css
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
Displays a "give me a star" + star count of the gtihub repo on the landing page
=> docs: :memo: add github star button to landing page

packages/signalstory/src/lib/store-history.ts
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
Agadoo tree-shakeability check fails.
acorn, which is used by agadoo, has problems with static class fields. This commit introduces global constants instead.
```
[ ] Yes
[x] No
```
=> refactor(core): :recycle: extract static field from HistoryTrackerBase to global constants

README.md, docs/docs/history.md, docs/docs/immutable-store.md, docs/docs/prolog.md, docs/docs/state-snapshot.md, docs/docs/store.md
=> docs(core): :memo: improve Readme and some docs sections

docs/docusaurus.config.js, package.json, packages/signalstory/README.md, packages/signalstory/package.json
=> chore: :hammer: release 17.4.0

docs/docs/building-blocks/event.md, docs/docs/store.md
- [ x] The commit message follows our guidelines
Fixes two typos in docs
```
[ ] Bugfix
[ ] Feature
[ x] Documentation content changes
```
Issue Number: N/A
```
[ ] Yes
[ x] No
```
=> docs: fix typos

.github/workflows/ci.yml
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
[x] Other... Please describe: Updated the CI pipeline to test on Node version 18, 20, and 22
```
Currently, the CI pipeline runs on Node 18
Now the CI pipeline runs on Node 18, 20, and 22
```
[ ] Yes
[x] No
```
=> ci: 🎡 run builds and testing across node 18, 20, and 22

docs/docusaurus.config.js
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
The announcement bar in the docs is on `18.0.0` but version `19.0.0` was released in December 2024. This is a small PR but it updates the announcement bar.
```
[ ] Yes
[x] No
```
=> docs: 📝 update the announcement bar to 19.0.0
